from __future__ import annotations

PRESETS = {
    "cool-professional": {
        "label": "清爽专业 / Resume",
        "background": "#FFFFFF",
        "ink": "#101828",
        "muted": "#667085",
        "line": "#D8E1EC",
        "blue": ("#2F6BFF", "#EEF4FF"),
        "cyan": ("#0F7C8A", "#EAF8F8"),
        "purple": ("#6B5BD6", "#F2EFFF"),
        "orange": ("#C86B1A", "#FFF3E8"),
        "green": ("#23845B", "#ECF8F1"),
        "red": ("#C2475C", "#FFF0F3"),
        "slate": ("#475467", "#F2F4F7"),
    },
    "portfolio-premium": {
        "label": "作品集质感 / Portfolio",
        "background": "#FEFEFF",
        "ink": "#161A2B",
        "muted": "#6C7284",
        "line": "#DADFEB",
        "blue": ("#4B68F2", "#F0F3FF"),
        "cyan": ("#187C86", "#EDF9F9"),
        "purple": ("#7759D8", "#F4F0FF"),
        "orange": ("#C26A22", "#FFF4E9"),
        "green": ("#2F8060", "#EDF8F2"),
        "red": ("#C44C64", "#FFF1F4"),
        "slate": ("#4B5568", "#F4F5F8"),
    },
    "academic-light": {
        "label": "学术克制 / Academic",
        "background": "#FFFFFF",
        "ink": "#172033",
        "muted": "#667085",
        "line": "#D9E0E8",
        "blue": ("#315A8A", "#EFF4F9"),
        "cyan": ("#36757A", "#F0F7F7"),
        "purple": ("#665E87", "#F4F2F8"),
        "orange": ("#9B6B3A", "#FAF5EF"),
        "green": ("#4E765E", "#F1F7F3"),
        "red": ("#9A5662", "#FAF2F4"),
        "slate": ("#596273", "#F4F6F8"),
    },
    "warm-business": {
        "label": "商务暖色 / Business",
        "background": "#FFFDFB",
        "ink": "#1E293B",
        "muted": "#6B7280",
        "line": "#E4DED7",
        "blue": ("#3567A8", "#EEF4FB"),
        "cyan": ("#287783", "#EEF8F8"),
        "purple": ("#7562A4", "#F5F1FA"),
        "orange": ("#C66A2B", "#FFF2E8"),
        "green": ("#4E7C5C", "#EEF7F1"),
        "red": ("#B24E55", "#FFF0F1"),
        "slate": ("#586271", "#F5F5F4"),
    },
}

MODE_DEFAULTS = {
    "resume": {"palette": "cool-professional", "density": "concise", "emphasis": "product_evolution"},
    "portfolio": {"palette": "portfolio-premium", "density": "balanced", "emphasis": "balanced"},
    "academic": {"palette": "academic-light", "density": "detailed", "emphasis": "technical"},
    "business": {"palette": "warm-business", "density": "balanced", "emphasis": "product_evolution"},
}
